name: tao_app_fixed_clean
description: "Tao of the Day App"

publish_to: 'none'

version: 1.0.0+48

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
#  just_audio: ^0.9.35
#  audio_service: ^0.18.9
#  audio_session: ^0.1.20
  http: ^1.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1  # â† Keep this commented out for now
  csv: ^5.0.3
  url_launcher: ^6.1.11
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.3
  flutter_launcher_icons: ^0.13.1

# ADD THIS SECTION for splash screen
flutter_native_splash:
  color: "#FFD26F"
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
    uses-material-design: true

    assets:
      - lib/data/tao_data.json

